### ISSUE TITLE
Update Content About page

### ISSUE THREAD

**Issue by quosi** [PyLadiesBerlin/PyLadiesBerlin.github.io#29]
- About PyLadies
- add organizers (LinkedIn / github)

- hero page, add youtube links
- hero text fixes
- add learning resources pages to menu
- add learning resources content from old PyLadies page

**Comment by mei-li** [comment]
I will make a new one for the learning resources

**Comment by mei-li** [comment]
I see the translated page says WIP, so that needs fixing

@quosi What else is missing here?

**Comment by sleepypioneer** [comment]
I believe this is covered by other issues including #39 #2
