### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/PyLadiesBerlin.github.io#59]
Probably the MIT license is sufficient

**Comment by marimeireles** [comment]
Can we have GPLv3 for the libre web? :)

**Comment by discombobulateme** [comment]
I would use MIT as it is more permissive, but both works for me :)

**Comment by discombobulateme** [comment]
Added: https://github.com/PyLadiesBerlin/PyLadiesBerlin.github.io/blob/main/LICENSE
