### ISSUE TITLE
Run Check my Repo on this repo

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/PyLadiesBerlin.github.io#62]
Check my Repo is an awesome tool developed by @discombobulateme for checking how well a repository does a job of being approachable for open source repositories. We should run it on this website repo and then make tickets for any suggestions it picks up on https://github.com/saucelabs/check-my-repo

**Comment by sleepypioneer** [comment]
I am assigning myself, I have forked the repo and set it up. I am now waiting for it to run the actions at the scheduled time/or when a change is merged to main to see the outcome.

**Comment by sleepypioneer** [comment]
Repo for check my repo is now in our account here https://github.com/PyLadiesBerlin/check-my-repo

**Comment by sleepypioneer** [comment]
Ok not sure I understood how to set it up correctly, @discombobulateme can you help :see_no_evil: I have the tool running here http://berlin.pyladies.com/check-my-repo/ but its checking sauce labs repositories not ours, did I miss a step?

**Comment by discombobulateme** [comment]
@sleepypioneer it is already working :) its made to work out of the box http://berlin.pyladies.com/check-my-repo/ <3 <3 <3

**Comment by sleepypioneer** [comment]
Actually this was not working until I enabled the scheduled actions, which I had not understood initially but turned on yesterday :)

**Comment by sleepypioneer** [comment]
![image](https://user-images.githubusercontent.com/23617373/155894203-cd203289-7b62-430a-b52f-328be49853bb.png)
All our repos fail :face_exhaling: but anyway this is the tags for this repo, I will create issues for any that don't already have one
