### ISSUE TITLE
Add Twitter feed

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/PyLadiesBerlin.github.io#68]
This should be possible with the Twitter API. considering how Twitter has evolved we may not want to do this.

**Comment by cmaureir** [comment]
En realidad sería solo una URL bastante sencilla, pero claro, si queremos darle más visibilidad a otras redes. Se obtiene en publish.twitter.com y se ingresa el username para seleccionar el frame y genera el código:

```
<a class="twitter-timeline" href="https://twitter.com/PyLadiesBer?ref_src=twsrc%5Etfw">Tweets by PyLadiesBer</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by sleepypioneer** [comment]
closing irrelevant.
